behaviors:
  BottleFlipEnv:
    trainer_type: ppo
    hyperparameters:
      batch_size: 200
      buffer_size: 10000
      learning_rate: 5.0e-5
      beta: 7.5e-3
      epsilon: 0.1
      lambd: 0.99
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      deterministic: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50000000
    time_horizon: 2048
    summary_freq: 10000
    threaded: true
